import type { DuelRecord, Item } from '@/types';
import { getHistory, saveHistory } from '@/lib/storage';

// ---------------------------------------------------------------------------
// Duel record creation (in-memory session tracking)
// ---------------------------------------------------------------------------

export function createDuelRecord(
  itemA: Item,
  itemB: Item,
  winner: Item | null,
  timestamp: number,
): DuelRecord {
  return {
    itemA: itemA.id,
    itemB: itemB.id,
    winner: winner?.id ?? null,
    timestamp,
  };
}

// ---------------------------------------------------------------------------
// History append
// ---------------------------------------------------------------------------

export function appendDuelToHistory(
  listId: string,
  listName: string,
  itemA: Item,
  itemB: Item,
  winner: Item | null,
): void {
  const today = new Date().toISOString().slice(0, 10);

  let entry: string;
  if (winner) {
    const loser = winner.id === itemA.id ? itemB : itemA;
    entry = `- ${winner.name} [${winner.id}] > ${loser.name} [${loser.id}]`;
  } else {
    entry = `- ${itemA.name} [${itemA.id}] = ${itemB.name} [${itemB.id}]`;
  }

  const current = getHistory(listId);
  const updated = tailParseAndAppend(current, entry, today, listName);
  saveHistory(listId, updated);
}

// ---------------------------------------------------------------------------
// Tail-parse and append
// ---------------------------------------------------------------------------

export function tailParseAndAppend(
  historyString: string,
  newEntry: string,
  date: string,
  listName: string,
): string {
  // Empty history — create from scratch
  if (!historyString.trim()) {
    return [
      `# ${listName} — Duel History`,
      `> Auto-generated by DuelList. 1 duels recorded.`,
      '',
      `## ${date}`,
      newEntry,
      '',
    ].join('\n');
  }

  // Increment duel count in line 2
  let result = historyString.replace(
    /^(> Auto-generated by DuelList\. )(\d+)( duels recorded\.)$/m,
    (_, prefix: string, count: string, suffix: string) =>
      `${prefix}${parseInt(count, 10) + 1}${suffix}`,
  );

  // Find the last date header
  const lastHeaderPos = result.lastIndexOf('\n## ');

  if (lastHeaderPos !== -1) {
    // Extract the date from the header
    const headerLineEnd = result.indexOf('\n', lastHeaderPos + 1);
    const headerLine =
      headerLineEnd === -1
        ? result.slice(lastHeaderPos + 1)
        : result.slice(lastHeaderPos + 1, headerLineEnd);
    const headerDate = headerLine.replace('## ', '').trim();

    if (headerDate === date) {
      // Same day — append entry at end
      const trimmed = result.trimEnd();
      result = trimmed + '\n' + newEntry + '\n';
    } else {
      // New day — add new date header
      const trimmed = result.trimEnd();
      result = trimmed + '\n\n## ' + date + '\n' + newEntry + '\n';
    }
  } else {
    // No date header found (shouldn't happen, but handle gracefully)
    const trimmed = result.trimEnd();
    result = trimmed + '\n\n## ' + date + '\n' + newEntry + '\n';
  }

  return result;
}

// ---------------------------------------------------------------------------
// Cooldown parsing — extract recent pairs from history
// ---------------------------------------------------------------------------

const DUEL_LINE_RE =
  /^- .+ \[([a-z0-9]{4})\] [>=] .+ \[([a-z0-9]{4})\]$/;

export function parseRecentPairs(
  historyString: string,
  listSize: number,
): Set<string> {
  const pairs = new Set<string>();
  if (!historyString) return pairs;

  const lines = historyString.split('\n');

  // Iterate backward (most recent first)
  for (let i = lines.length - 1; i >= 0 && pairs.size < listSize; i--) {
    const line = lines[i]!;
    const match = DUEL_LINE_RE.exec(line);
    if (match) {
      const key = createPairKey(match[1]!, match[2]!);
      pairs.add(key);
    }
  }

  return pairs;
}

export function createPairKey(id1: string, id2: string): string {
  return id1 < id2 ? `${id1}:${id2}` : `${id2}:${id1}`;
}
