import type { DuelRecord, Item } from '@/types';
import { getHistory, saveHistory, markDuelRecorded } from '@/lib/storage';
import { formatLocalDate } from '@/lib/datetime';

// ---------------------------------------------------------------------------
// Duel record creation (in-memory session tracking)
// ---------------------------------------------------------------------------

export function getDuelCountFromHistory(historyString: string): number {
  const m = historyString.match(
    /^> Auto-generated by Duel⚡List\. (\d+) duels recorded\.$/m,
  );
  return m?.[1] ? parseInt(m[1], 10) : 0;
}

export function createDuelRecord(
  itemA: Item,
  itemB: Item,
  winner: Item | null,
  timestamp: number,
): DuelRecord {
  return {
    itemA: itemA.id,
    itemB: itemB.id,
    winner: winner?.id ?? null,
    timestamp,
  };
}

// ---------------------------------------------------------------------------
// History append
// ---------------------------------------------------------------------------

export function appendDuelToHistory(
  listId: string,
  listName: string,
  itemA: Item,
  itemB: Item,
  winner: Item | null,
): void {
  const now = new Date();
  const today = formatLocalDate(now);
  const iso = now.toISOString(); // e.g. 2026-04-23T14:32:05.847Z

  let entry: string;
  if (winner) {
    // Preserve presentation order. ">" = left won, "<" = right won.
    const op = winner.id === itemA.id ? '>' : '<';
    entry = `- ${itemA.name} [${itemA.id}] ${op} ${itemB.name} [${itemB.id}] @${iso}`;
  } else {
    entry = `- ${itemA.name} [${itemA.id}] = ${itemB.name} [${itemB.id}] @${iso}`;
  }

  const current = getHistory(listId);
  const updated = tailParseAndAppend(current, entry, today, listName);
  saveHistory(listId, updated);
  markDuelRecorded(listId);
}

// ---------------------------------------------------------------------------
// Tail-parse and append
// ---------------------------------------------------------------------------

export function tailParseAndAppend(
  historyString: string,
  newEntry: string,
  date: string,
  listName: string,
): string {
  // Empty history.create from scratch
  if (!historyString.trim()) {
    return [
      `# ${listName}.Duel History`,
      `> Auto-generated by Duel⚡List. 1 duels recorded.`,
      '',
      `## ${date}`,
      newEntry,
      '',
    ].join('\n');
  }

  // Increment duel count in line 2
  let result = historyString.replace(
    /^(> Auto-generated by Duel⚡List\. )(\d+)( duels recorded\.)$/m,
    (_, prefix: string, count: string, suffix: string) =>
      `${prefix}${parseInt(count, 10) + 1}${suffix}`,
  );

  // Find the last date header
  const lastHeaderPos = result.lastIndexOf('\n## ');

  if (lastHeaderPos !== -1) {
    // Extract the date from the header
    const headerLineEnd = result.indexOf('\n', lastHeaderPos + 1);
    const headerLine =
      headerLineEnd === -1
        ? result.slice(lastHeaderPos + 1)
        : result.slice(lastHeaderPos + 1, headerLineEnd);
    const headerDate = headerLine.replace('## ', '').trim();

    if (headerDate === date) {
      // Same day.append entry at end
      const trimmed = result.trimEnd();
      result = trimmed + '\n' + newEntry + '\n';
    } else {
      // New day.add new date header
      const trimmed = result.trimEnd();
      result = trimmed + '\n\n## ' + date + '\n' + newEntry + '\n';
    }
  } else {
    // No date header found (shouldn't happen, but handle gracefully)
    const trimmed = result.trimEnd();
    result = trimmed + '\n\n## ' + date + '\n' + newEntry + '\n';
  }

  return result;
}

// ---------------------------------------------------------------------------
// Cooldown parsing.extract recent pairs from history
// ---------------------------------------------------------------------------

const DUEL_LINE_RE =
  /^- .+ \[([a-z0-9]{4})\] [><=] .+ \[([a-z0-9]{4})\](?: @\S+)?$/;

export function parseRecentPairs(
  historyString: string,
  listSize: number,
): Set<string> {
  const pairs = new Set<string>();
  if (!historyString) return pairs;

  const lines = historyString.split('\n');

  // Iterate backward (most recent first)
  for (let i = lines.length - 1; i >= 0 && pairs.size < listSize; i--) {
    const line = lines[i]!;
    const match = DUEL_LINE_RE.exec(line);
    if (match) {
      const key = createPairKey(match[1]!, match[2]!);
      pairs.add(key);
    }
  }

  return pairs;
}

export function createPairKey(id1: string, id2: string): string {
  return id1 < id2 ? `${id1}:${id2}` : `${id2}:${id1}`;
}

// ---------------------------------------------------------------------------
// Per-item history scan
// ---------------------------------------------------------------------------

export type ItemDuelRecord = {
  tsIso: string | null;
  opponentId: string;
  opponentName: string;
  outcome: 'win' | 'loss' | 'tie';
};

// Captures: nameA, idA, op, nameB, idB, optional @<ts>
const FULL_DUEL_LINE_RE =
  /^- (.+?) \[([a-z0-9]{4})\] ([><=]) (.+?) \[([a-z0-9]{4})\](?: @(\S+))?$/;

function* iterDuelLines(historyString: string): Generator<{
  nameA: string;
  idA: string;
  op: '>' | '<' | '=';
  nameB: string;
  idB: string;
  tsIso: string | null;
}> {
  if (!historyString) return;
  const lines = historyString.split('\n');
  for (const line of lines) {
    const m = FULL_DUEL_LINE_RE.exec(line);
    if (!m) continue;
    const tsRaw = m[6] ?? null;
    const tsIso = tsRaw && /^\d{4}-\d{2}-\d{2}T/.test(tsRaw) ? tsRaw : null;
    yield {
      nameA: m[1]!,
      idA: m[2]!,
      op: m[3] as '>' | '<' | '=',
      nameB: m[4]!,
      idB: m[5]!,
      tsIso,
    };
  }
}

/**
 * Return up to `limit` duels involving `itemId`, newest first.
 * Iterates the file bottom-up; matches are name-stable across renames because
 * the lookup key is the item ID.
 */
export function parseHistoryByItem(
  historyString: string,
  itemId: string,
  limit = 10,
): ItemDuelRecord[] {
  const records: ItemDuelRecord[] = [];
  const all = [...iterDuelLines(historyString)];
  for (let i = all.length - 1; i >= 0 && records.length < limit; i--) {
    const e = all[i]!;
    const isA = e.idA === itemId;
    const isB = e.idB === itemId;
    if (!isA && !isB) continue;
    let outcome: 'win' | 'loss' | 'tie';
    if (e.op === '=') outcome = 'tie';
    else if (e.op === '>') outcome = isA ? 'win' : 'loss';
    else outcome = isB ? 'win' : 'loss';
    records.push({
      tsIso: e.tsIso,
      opponentId: isA ? e.idB : e.idA,
      opponentName: isA ? e.nameB : e.nameA,
      outcome,
    });
  }
  return records;
}

export type ItemStats = {
  wins: number;
  losses: number;
  ties: number;
  total: number;
  lastDuelTs: number | null;
};

export function computeItemStats(
  historyString: string,
  itemId: string,
): ItemStats {
  let wins = 0;
  let losses = 0;
  let ties = 0;
  let lastDuelTs: number | null = null;
  for (const e of iterDuelLines(historyString)) {
    const isA = e.idA === itemId;
    const isB = e.idB === itemId;
    if (!isA && !isB) continue;
    if (e.op === '=') ties++;
    else if (e.op === '>') (isA ? wins++ : losses++);
    else (isB ? wins++ : losses++);
    if (e.tsIso) {
      const ts = new Date(e.tsIso).getTime();
      if (!isNaN(ts) && (lastDuelTs === null || ts > lastDuelTs)) {
        lastDuelTs = ts;
      }
    }
  }
  return { wins, losses, ties, total: wins + losses + ties, lastDuelTs };
}

export type OpponentStats = {
  opponentId: string;
  opponentName: string;
  wins: number;
  losses: number;
  ties: number;
  total: number;
};

/**
 * Aggregate this item's record against every opponent it has duelled.
 * Outcomes are from the perspective of `itemId`.
 */
export function computeOpponentStats(
  historyString: string,
  itemId: string,
): OpponentStats[] {
  const map = new Map<string, OpponentStats>();
  for (const e of iterDuelLines(historyString)) {
    const isA = e.idA === itemId;
    const isB = e.idB === itemId;
    if (!isA && !isB) continue;
    const opponentId = isA ? e.idB : e.idA;
    const opponentName = isA ? e.nameB : e.nameA;
    let entry = map.get(opponentId);
    if (!entry) {
      entry = { opponentId, opponentName, wins: 0, losses: 0, ties: 0, total: 0 };
      map.set(opponentId, entry);
    } else {
      // Keep the most recent name we see (handles renames).
      entry.opponentName = opponentName;
    }
    if (e.op === '=') entry.ties++;
    else if (e.op === '>') (isA ? entry.wins++ : entry.losses++);
    else (isB ? entry.wins++ : entry.losses++);
    entry.total++;
  }
  return [...map.values()];
}

// ---------------------------------------------------------------------------
// Undo support
// ---------------------------------------------------------------------------

/**
 * Remove the most recent duel entry from a history markdown string. Decrements
 * the duels-recorded counter and drops a date section that becomes empty.
 * Returns the original string unchanged when no entry is found.
 */
export function removeLastDuelFromHistory(historyString: string): string {
  if (!historyString.trim()) return historyString;
  const lines = historyString.split('\n');

  // Find the last duel line.
  let removeIdx = -1;
  for (let i = lines.length - 1; i >= 0; i--) {
    if (DUEL_LINE_RE.test(lines[i]!)) {
      removeIdx = i;
      break;
    }
  }
  if (removeIdx === -1) return historyString;
  lines.splice(removeIdx, 1);

  // Find the date header that owns this entry and check whether the section
  // still has any duels.
  let headerIdx = -1;
  for (let i = removeIdx - 1; i >= 0; i--) {
    if (lines[i]!.startsWith('## ')) {
      headerIdx = i;
      break;
    }
  }
  if (headerIdx !== -1) {
    let hasEntries = false;
    for (let i = headerIdx + 1; i < lines.length; i++) {
      if (lines[i]!.startsWith('## ')) break;
      if (DUEL_LINE_RE.test(lines[i]!)) {
        hasEntries = true;
        break;
      }
    }
    if (!hasEntries) {
      let dropFrom = headerIdx;
      if (dropFrom > 0 && lines[dropFrom - 1]!.trim() === '') dropFrom--;
      let dropTo = headerIdx;
      while (dropTo + 1 < lines.length && lines[dropTo + 1]!.trim() === '') dropTo++;
      lines.splice(dropFrom, dropTo - dropFrom + 1);
    }
  }

  let result = lines.join('\n');
  result = result.replace(
    /^(> Auto-generated by Duel⚡List\. )(\d+)( duels recorded\.)$/m,
    (_, prefix: string, count: string, suffix: string) => {
      const n = Math.max(0, parseInt(count, 10) - 1);
      return `${prefix}${n}${suffix}`;
    },
  );
  return result;
}
