import type { Item, ListConfig } from '@/types';

function makeItem(id: string, name: string, rank: number): Item {
  return {
    id,
    name,
    eloScore: 1000,
    prevEloScore: 1000,
    prevRank: rank,
    comparisonCount: 0,
    added: '2026-04-21',
  };
}

const SAMPLE_DATA: Record<string, { name: string; items: string[] }> = {
  anime: {
    name: 'Top Anime',
    items: [
      'One Piece',
      'Attack on Titan',
      'Naruto',
      'Fullmetal Alchemist: Brotherhood',
      'Death Note',
      'Demon Slayer',
      'Jujutsu Kaisen',
      'My Hero Academia',
      'Steins;Gate',
      'Cowboy Bebop',
      'Hunter x Hunter',
      'Spy x Family',
      'Vinland Saga',
      'Mob Psycho 100',
      'One Punch Man',
      'Chainsaw Man',
      'Bleach',
    ],
  },
  pizza: {
    name: 'Pizza Toppings',
    items: [
      'Pepperoni',
      'Mushroom',
      'Onion',
      'Sausage',
      'Bacon',
      'Basil',
      'Black Olive',
      'Extra Cheese',
      'Garlic',
      'Tomato',
      'Pineapple',
      'Jalapeño',
      'Anchovy',
    ],
  },
  movies: {
    name: 'Favorite Movies',
    items: [
      'The Shawshank Redemption',
      'Inception',
      'The Dark Knight',
      'Pulp Fiction',
      'Forrest Gump',
      'The Matrix',
      'Interstellar',
      'Fight Club',
      'The Godfather',
      'Goodfellas',
      'Parasite',
      'Spirited Away',
      'Whiplash',
      'Eternal Sunshine of the Spotless Mind',
      'Mad Max: Fury Road',
      'No Country for Old Men',
    ],
  },
  vacation: {
    name: 'Vacation Destinations',
    items: [
      'Tokyo',
      'Paris',
      'New York',
      'Bali',
      'London',
      'Rome',
      'Barcelona',
      'Reykjavik',
      'Maldives',
      'Cape Town',
      'Lisbon',
      'Kyoto',
      'Buenos Aires',
      'Sydney',
    ],
  },
  snacks: {
    name: 'Best Snacks',
    items: [
      'Chips',
      'Popcorn',
      'Chocolate',
      'Pretzels',
      'Cookies',
      'Trail Mix',
      'Gummy Bears',
      'Nachos',
      'Ice Cream',
      'Fruit',
      'Beef Jerky',
      'Cheese Cubes',
    ],
  },
  hobbies: {
    name: 'Hobbies',
    items: [
      'Reading',
      'Gaming',
      'Cooking',
      'Hiking',
      'Photography',
      'Drawing',
      'Gardening',
      'Music',
      'Cycling',
      'Yoga',
      'Writing',
      'Birdwatching',
      'Climbing',
      'Knitting',
      'Woodworking',
      'Pottery',
      'Surfing',
      'Chess',
    ],
  },
  games: {
    name: 'Video Games',
    items: [
      'The Legend of Zelda: Breath of the Wild',
      'Elden Ring',
      'Dark Souls',
      'Hollow Knight',
      'Hades',
      'Stardew Valley',
      'Portal 2',
      'Half-Life 2',
      'Red Dead Redemption 2',
      'The Witcher 3',
      'Celeste',
      'Disco Elysium',
      'Minecraft',
      'Tetris',
      'Mass Effect 2',
    ],
  },
  books: {
    name: 'Books to Read',
    items: [
      'The Lord of the Rings',
      'Dune',
      '1984',
      'Brave New World',
      'The Great Gatsby',
      'To Kill a Mockingbird',
      'Crime and Punishment',
      'Catch-22',
      'Slaughterhouse-Five',
      'The Name of the Wind',
      'Project Hail Mary',
      'Foundation',
      'Neuromancer',
      'A Wizard of Earthsea',
      'The Road',
      'Beloved',
      'Cloud Atlas',
    ],
  },
  boardgames: {
    name: 'Board Games',
    items: [
      'Catan',
      'Carcassonne',
      'Ticket to Ride',
      'Pandemic',
      'Wingspan',
      'Azul',
      'Splendor',
      '7 Wonders',
      'Terraforming Mars',
      'Gloomhaven',
      'Codenames',
      'Risk',
      'Scythe',
    ],
  },
  shows: {
    name: 'TV Shows',
    items: [
      'Breaking Bad',
      'The Wire',
      'The Sopranos',
      'Game of Thrones',
      'Better Call Saul',
      'Succession',
      'Mad Men',
      'Chernobyl',
      'Fleabag',
      'Arcane',
      'Severance',
      'The Office',
      'Seinfeld',
      'Twin Peaks',
      'True Detective',
      'Stranger Things',
    ],
  },
  chatbots: {
    name: 'AI Chatbots',
    items: [
      'ChatGPT',
      'Claude',
      'Gemini',
      'Copilot',
      'Perplexity',
      'Grok',
      'Llama',
      'Mistral',
      'DeepSeek',
      'Meta AI',
      'Pi',
      'Character.AI',
      'Qwen',
    ],
  },
  starters: {
    name: 'Pokémon Starters',
    items: [
      'Bulbasaur',
      'Charmander',
      'Squirtle',
      'Chikorita',
      'Cyndaquil',
      'Totodile',
      'Treecko',
      'Torchic',
      'Mudkip',
      'Turtwig',
      'Chimchar',
      'Piplup',
      'Snivy',
      'Tepig',
      'Oshawott',
      'Chespin',
    ],
  },
};

// Deterministic IDs for sample items (4-char each, indexed by item position).
const SAMPLE_IDS = [
  'sa01', 'sa02', 'sa03', 'sa04', 'sa05',
  'sa06', 'sa07', 'sa08', 'sa09', 'sa10',
  'sa11', 'sa12', 'sa13', 'sa14', 'sa15',
  'sa16', 'sa17', 'sa18', 'sa19', 'sa20',
];

const SAMPLE_LIST_IDS: Record<string, string> = {
  anime: 'sani',
  pizza: 'spiz',
  movies: 'smov',
  vacation: 'svac',
  snacks: 'ssnk',
  hobbies: 'shob',
  games: 'sgam',
  books: 'sbok',
  boardgames: 'sbgm',
  shows: 'sshw',
  chatbots: 'scbt',
  starters: 'spkm',
};

export function getSampleList(key: string): ListConfig | null {
  const data = SAMPLE_DATA[key];
  if (!data) return null;

  const items = data.items.map((name, idx) =>
    makeItem(SAMPLE_IDS[idx]!, name, idx + 1),
  );

  return {
    id: SAMPLE_LIST_IDS[key]!,
    name: data.name,
    sessionLength: 10,
    kFactor: 32,
    created: '2026-04-21',
    items: structuredClone(items),
  };
}

export const SAMPLE_KEYS = Object.keys(SAMPLE_DATA);
