/**
 * UI string constants.all user-visible text lives here.
 * Prep for Phase 3 i18n: swap this module for translation JSON files later.
 */

export const S = {
  app: {
    name: 'DuelList',
    tagline: 'Rank anything.one duel at a time.',
    storageAlmostFull:
      'Storage is almost full. Export your lists to free up space.',
    appSettingsAria: 'App settings',
    goBackAria: 'Go back',
    errorBoundaryTitle: 'Something went wrong',
    errorBoundaryDescription:
      'DuelList hit an unexpected error. Your saved lists are safe.reloading usually fixes it.',
    errorBoundaryReload: 'Reload',
    errorBoundaryDetails: 'Show details',
    footerNavAria: 'Footer navigation',
    footerGlossary: 'Glossary',
    footerFeatures: 'Features',
    footerSettings: 'Settings',
    footerVersion: (v: string) => `v${v}`,
    themeToggleAria: (current: string, next: string) =>
      `Theme: ${current}. Tap to switch to ${next}.`,
  },

  common: {
    listNotFound: 'List not found',
    pageNotFound: 'Page not found',
    pageNotFoundDescription: "The page you're looking for doesn't exist.",
    goHome: 'Go home',
    goToHome: 'Go to home',
    back: 'Back',
    backToList: 'Back to list',
    backAria: 'Back',
    export: 'Export',
    clear: 'Clear',
    clearFilter: 'Clear filter',
    cancel: 'Cancel',
    add: 'Add',
    next: 'Next',
    create: 'Create',
    delete: 'Delete',
    remove: 'Remove',
    save: 'Save',
    confirmRename: 'Confirm rename',
    saveName: 'Save name',
    editName: 'Edit name',
    helpAria: (term: string) => `What does "${term}" mean?`,
  },

  home: {
    emptyTitle: 'No lists yet',
    emptyDescription: 'Create one or import a markdown file.',
    createList: 'Create list',
    importList: 'Import list',
    openFile: 'Open file',
    open: 'Open',
    new: 'New',
    reorder: 'Reorder',
    done: 'Done',
    sortLabel: 'Sort lists',
    sortBy: 'Sort by',
    sortRecent: 'Recent',
    sortAZ: 'A–Z',
    sortCreated: 'Created',
    sortCustom: 'Custom',
    sortFieldRecent: 'Recent',
    sortFieldName: 'Name',
    sortFieldCreated: 'Created',
    sortFieldCustom: 'Custom',
    sortDirAriaRecentDesc: 'Most recent first.tap to reverse',
    sortDirAriaRecentAsc: 'Oldest first.tap to reverse',
    sortDirAriaNameAsc: 'A to Z.tap to reverse',
    sortDirAriaNameDesc: 'Z to A.tap to reverse',
    sortDirAriaCreatedDesc: 'Newest first.tap to reverse',
    sortDirAriaCreatedAsc: 'Oldest first.tap to reverse',
    heroTitle: 'Ready for a duel?',
    heroSubtitle: 'Pick a winner from a random match-up.',
    heroAction: 'Random duel',
    heroNoneEligibleHint: 'Add 2+ items to a list to enable duels.',
  },

  welcome: {
    heading: 'Welcome to DuelList',
    description:
      'Rank your favourites through quick A-vs-B comparisons. Create a list, add items, and start duelling.',
    getStarted: 'Get started',
    trySample: 'Try a sample list',
    skipTour: 'Skip tour',
    seeAllFeatures: 'See all features',
    stepAria: (n: number) => `Step ${n}`,
    duelStepTitle: 'The Duel',
    duelStepDescription:
      'Two items appear side by side. Pick the winner, declare a tie, or skip.',
    rankingStepTitle: 'Your Ranking Builds Itself',
    rankingStepDescription:
      'After each duel, your list re-ranks automatically. The more duels you do, the more accurate it gets.',
    sessionsStepTitle: 'Quick Sessions',
    sessionsStepDescription: "Do 5–10 duels a day. It's a habit, not a chore.",
    remindersStepTitle: 'Gentle Nudges',
    remindersStepDescription:
      'Pick a cadence and DuelList will surface a list that’s gone stale. In-app banner, OS notification, or both.quiet hours respected.',
    readyStepTitle: 'Ready!',
    readyStepDescription: 'Create a list or try a sample to get started.',
  },

  duel: {
    skipLabel: 'Skip (tie)',
    sessionComplete: 'Session complete!',
    needTwoItems: 'Add at least 2 items to start duelling.',
    tie: 'Tie',
    skip: 'Skip',
    duelsCompleted: (n: number) => `${n} duels completed`,
    currentTop3: 'Current Top 3',
    biggestMovers: 'Biggest Movers',
    rankings: 'Rankings',
    newSession: 'New session',
    noMorePairs: 'No more pairs available',
    backToRankings: 'Back to rankings',
    keyboardHint: '← / → to pick · T for tie · S to skip',
    swipeUpToPick: 'Swipe up to pick',
    swipeHelpText: 'Swipe up or tap to pick · ← / → keys work too',
    pickAria: (name: string) => `Pick ${name}`,
    pickBadge: 'PICK',
    scoreSuffix: (n: number) => `${n} pts`,
  },

  ranking: {
    addItemsPrompt: 'Add some items to get started.',
    startComparing: 'Start comparing to see rankings change.',
    startDuel: 'Start duelling',
    heroSubtitle: 'Compare two items, sharpen the ranking',
    rank: 'Rank',
    score: 'Score',
    rankTooltip: 'Rank',
    scoreTooltip: 'Score',
    duelsPlayed: (n: number) => `${n} ${n === 1 ? 'duel' : 'duels'} played`,
    switchToRank: 'Switch to rank display',
    switchToScore: 'Switch to score display',
    addItems: 'Add items',
    historyAria: 'Duel history',
    addItemsAria: 'Add items',
    settingsAria: 'List settings',
    fileLinked: 'File linked',
    fileLinkedTooltip: 'File linked',
    fileLinkBroken: 'File link broken',
    fileLinkBrokenTooltip: 'File link broken.re-link in settings',
    fileNotLinked: 'Not linked to a file',
    fileNotLinkedTooltip:
      'Not linked to a file.tap to link',
    linkFileConfirmTitle: 'Link list to a file?',
    linkFileConfirmMessage:
      'Pick or create a Markdown file on disk. DuelList will write changes to it as you go, so you keep a portable copy of this list.',
    relinkFileConfirmMessage:
      'The previously linked file is no longer accessible. Pick the file again (or a new one) to restore the link.',
    optionsAria: (name: string) => `Options for ${name}`,
    renameAria: (name: string) => `Rename ${name}`,
    renameAction: 'Rename',
    removeAction: 'Remove',
    detailsAction: 'Details',
    removeItemTitle: 'Remove item',
    removeItemMessage: (name: string) =>
      `Remove "${name}" from the ranking? You can restore it later.`,
    removedHeading: (n: number) => `Removed (${n})`,
    removedExpandAria: 'Show removed items',
    removedCollapseAria: 'Hide removed items',
    restoreItemAria: (name: string) => `Restore ${name}`,
    restoreAction: 'Restore',
    removedItemMeta: (elo: number, duels: number) =>
      `${Math.round(elo)} pts · ${duels} ${duels === 1 ? 'duel' : 'duels'}`,
    filterPlaceholder: 'Filter items… (press /)',
    filterAria: 'Filter items',
    noMatch: (query: string) => `No items match “${query}”.`,
    restoreKeepsStatsHint: 'Restoring keeps these stats.',
    movedUp: (n: number) => `Moved up ${n}`,
    movedDown: (n: number) => `Moved down ${n}`,
    noChange: 'No change',
    topItemPrefix: (name: string) => `#1 ${name}`,
    itemsCount: (n: number) => `${n} items`,
    sortLabel: 'Sort',
    sortRankDesc: 'Rank.best first',
    sortRankAsc: 'Rank.worst first',
    sortScoreDesc: 'Score.high to low',
    sortScoreAsc: 'Score.low to high',
    sortAddedDesc: 'Added.newest first',
    sortAddedAsc: 'Added.oldest first',
    sortNameAsc: 'Name.A to Z',
    sortNameDesc: 'Name.Z to A',
    sortFieldRank: 'Rank',
    sortFieldScore: 'Score',
    sortFieldAdded: 'Added',
    sortFieldName: 'Name',
    sortDirAriaRankDesc: 'Best first.tap to reverse',
    sortDirAriaRankAsc: 'Worst first.tap to reverse',
    sortDirAriaScoreDesc: 'Highest score first.tap to reverse',
    sortDirAriaScoreAsc: 'Lowest score first.tap to reverse',
    sortDirAriaAddedDesc: 'Newest first.tap to reverse',
    sortDirAriaAddedAsc: 'Oldest first.tap to reverse',
    sortDirAriaNameAsc: 'A to Z.tap to reverse',
    sortDirAriaNameDesc: 'Z to A.tap to reverse',
    detailsTitle: 'Item details',
    detailsRank: 'Rank',
    detailsScore: 'Score',
    detailsAdded: 'Added',
    detailsLastDuel: 'Last duel',
    detailsNever: 'Never',
    detailsWins: 'Wins',
    detailsLosses: 'Losses',
    detailsTies: 'Ties',
    detailsTotal: 'Total duels',
    detailsNotesLabel: 'Notes',
    detailsNotesPlaceholder: 'Add notes about this item…',
    detailsNoNotes: 'No notes yet.',
    detailsLastDuels: 'Last duels',
    detailsNoDuelsYet: 'No duels yet.',
    detailsViewAllDuels: 'View all duels',
    detailsOutcomeWin: 'Won vs',
    detailsOutcomeLoss: 'Lost to',
    detailsOutcomeTie: 'Tied with',
  },

  list: {
    deleteConfirm: 'Are you sure you want to delete this list?',
    noItems: 'No items yet. Add some to get started.',
    name: 'Name',
    addItemsTitle: 'Add items',
    addItemsHelp: 'One item per line',
    addItemsPlaceholder: 'Naruto\nOne Piece\nAttack on Titan',
    namePlaceholder: 'My Top Anime',
    templateItemCount: (n: number) => `${n} items`,
    quickStartHeading: 'Quick start',
    quickStartDesc: 'Tap a template to create the list now with default settings.',
    neverOpened: 'Never opened',
    notLinkedShort: 'Not linked',
    filterPlaceholder: 'Filter lists… (press /)',
    filterAria: 'Filter lists',
    noMatch: (query: string) => `No lists match “${query}”.`,
    justNow: 'Just now',
    minutesAgo: (n: number) => `${n}m ago`,
    hoursAgo: (n: number) => `${n}h ago`,
    yesterday: 'Yesterday',
    daysAgo: (n: number) => `${n}d ago`,
    draggableAria: (name: string) => `${name}, draggable`,
    dragAria: (name: string) => `Drag ${name}`,
    moveUpAria: (name: string) => `Move ${name} up`,
    moveDownAria: (name: string) => `Move ${name} down`,
    duelsCount: (n: number) => `${n} ${n === 1 ? 'duel' : 'duels'}`,
    addMoreItemsCta: (n: number) =>
      n === 1 ? 'Add 1 more item to start' : `Add ${n} more items to start`,
    noDuelsYet: 'No duels yet',
    activityFresh: 'Recently duelled',
    activityStale: 'Hasn’t been duelled in a while',
    activityCold: 'Long time, no duel',
    activityNever: 'Never opened',
    podiumPositionAria: (pos: number, name: string) => `Position ${pos}: ${name}`,
    quickDuelAria: (name: string) => `Start a duel for ${name}`,
  },

  glossary: {
    heading: 'What things mean',
    intro: 'A reference for the terms, icons, colors, and labels you’ll see around DuelList.',
    backAria: 'Back to settings',
    openLink: 'What things mean',
    sectionTerminology: 'What we call things',
    termListLabel: 'List',
    termListDesc: 'A top-level collection on the home page (e.g. “Movies to rank”).',
    termItemLabel: 'Item',
    termItemDesc: 'A single thing inside a list. The members you compare.',
    termItemListLabel: 'Item list',
    termItemListDesc: 'The list of items shown inside one list.used to disambiguate from the home-page lists.',
    termDuelLabel: 'Duel',
    termDuelDesc: 'One head-to-head comparison between two items.',
    termSessionLabel: 'Session',
    termSessionDesc: 'A sequence of duels in one sitting. Length is set in app settings.',
    termScoreLabel: 'Score',
    termScoreDesc: 'A number per item that goes up when it wins, down when it loses. Powered by the ELO rating algorithm.',
    termRankLabel: 'Rank',
    termRankDesc: 'An item’s position (#1, #2…) derived from its score.',
    termBrandLabel: 'DuelList',
    termBrandDesc: 'The app you’re using. Always one word, capital D and L.',
    termReminderLabel: 'Reminder',
    termReminderDesc:
      'A nudge to play a duel for a list that’s gone quiet. Shows as a banner inside the app and.if you opt in.as an OS notification when the app is in the background.',
    termCadenceLabel: 'Cadence',
    termCadenceDesc:
      'How often reminders may fire.daily, weekly, monthly, or a custom interval. Set per app, not per list.',
    termQuietHoursLabel: 'Quiet hours',
    termQuietHoursDesc:
      'A daily window when reminders are suppressed (defaults are off). A reminder due during quiet hours waits until the window ends.',
    termSnoozeLabel: 'Snooze',
    termSnoozeDesc:
      'Action on the reminder banner that suppresses the suggested list for 24 hours. Skip just dismisses this reminder.the next eligible list will be offered next cycle.',
    sectionActivity: 'List activity dot',
    sectionFileLink: 'File link status',
    sectionRankingView: 'Ranking view',
    sectionQuickActions: 'Quick actions',
    sectionTrend: 'Trend arrows',
    sectionCardStates: 'List card states',
    sectionReminder: 'Reminder banner',
    sectionRemoved: 'Removed items',
    activityFreshDesc: 'Duelled in the last 14 days.',
    activityStaleDesc: 'Duelled 14–45 days ago, or opened but never duelled.',
    activityColdDesc: 'No duels in over 45 days.the ranking is going stale.',
    activityNeverDesc: 'You haven’t opened this list yet.',
    fileLinkedLabel: 'Synced to file',
    fileLinkedDesc: 'List is linked to a markdown file on disk and writes back when you change it.',
    fileBrokenLabel: 'Sync broken',
    fileBrokenDesc: 'The linked file can’t be reached. Re-link from list settings to fix.',
    fileNotLinkedLabel: 'Not linked',
    fileNotLinkedDesc: 'List lives only in DuelList. You can link it to a file from list settings.',
    rankViewLabel: 'Rank view',
    rankViewDesc: 'Shows ordinal positions (1, 2, 3…).',
    scoreViewLabel: 'Score view',
    scoreViewDesc: 'Shows the underlying score each item earns from duels (calculated with the ELO algorithm).',
    actionHistoryLabel: 'History',
    actionHistoryDesc: 'See past duels for this list.',
    actionAddLabel: 'Add items',
    actionAddDesc: 'Add one or more items to the list.',
    actionSettingsLabel: 'List settings',
    actionSettingsDesc: 'Rename, link to a file, export, or delete.',
    trendUpLabel: 'Moved up',
    trendUpDesc: 'This item climbed the ranking after the last duel.',
    trendDownLabel: 'Moved down',
    trendDownDesc: 'This item dropped in the ranking after the last duel.',
    cardCtaAddLabel: 'Add more items',
    cardCtaAddDesc: 'A list needs at least two items before you can duel.',
    cardCtaNoDuelsLabel: 'No duels yet',
    cardCtaNoDuelsDesc: 'Items are added but you haven’t duelled yet.open the list to start.',
    cardPodiumLabel: 'Top three',
    cardPodiumDesc: 'Once you’ve duelled, the current top three appear on the card.',
    reminderBellLabel: 'Reminder',
    reminderBellDesc: 'Suggests a list that hasn’t been duelled recently.',
    reminderSwordsLabel: 'Play action',
    reminderSwordsDesc: 'Tap to jump straight into a duel for the suggested list.',
    removedLabel: 'Removed item',
    removedDesc: 'Strike-through items were removed from the ranking. Restoring keeps their score and duel history.',
  },

  reminders: {
    bannerTitle: 'Time for a duel?',
    bannerSubtitle: (listName: string, days: number) =>
      days <= 0
        ? `Rank one duel for "${listName}".`
        : `Rank one duel for "${listName}".last played ${days} ${days === 1 ? 'day' : 'days'} ago.`,
    play: 'Play',
    snooze: 'Snooze 1d',
    skip: 'Skip',
    dismissAria: 'Dismiss reminder',
  },

  history: {
    title: 'Duel history',
    emptyDescription: 'No duels yet. Play a session to start building history.',
    startDuel: 'Start a duel',
    statTotal: 'Total duels',
    statTies: 'Ties',
    statTopWinner: 'Top winner',
    statBiggestRivalry: 'Biggest rivalry',
    sparklineRangeLabel: 'Last 30 days',
    sparklineAria: 'Duels per day, last 30 days',
    filterPlaceholder: 'Filter by name… (press /)',
    filterAria: 'Filter duels by name',
    noMatch: (query: string) => `No duels match “${query}”.`,
    showingOf: (shown: number, total: number) =>
      `Showing ${shown} of ${total} ${total === 1 ? 'duel' : 'duels'}.`,
    totalDuels: (n: number) =>
      `${n} ${n === 1 ? 'duel' : 'duels'}`,
    winsCount: (n: number) => `${n} ${n === 1 ? 'win' : 'wins'}`,
    meetingsCount: (n: number) =>
      `${n} ${n === 1 ? 'meeting' : 'meetings'}`,
    sparklineDay: (date: string, n: number) =>
      `${date}: ${n} ${n === 1 ? 'duel' : 'duels'}`,
    vsBadge: 'VS',
    tieBadge: 'TIE',
    versusAria: 'versus',
    tieAria: 'Tie',
    winnerAria: 'Winner',
    exportHistoryAria: 'Export history',
  },

  settings: {
    title: 'Settings',
    kFactorLabel: 'Ranking sensitivity',
    kFactorQuick: 'Quick (K=48)',
    kFactorGradual: 'Gradual (K=32)',
    kFactorTight: 'Tight (K=16)',
    sessionLengthLabel: 'Session length',
    sessionLengthUnit: 'duels',
    sessionLengthUnlimited: 'Unlimited',
    themeLabel: 'Theme',
    themeSystem: 'System',
    themeLight: 'Light',
    themeDark: 'Dark',
    duelModeLabel: 'Duel mode',
    duelModeSideBySide: 'Side-by-side cards',
    duelModeSwipe: 'Swipe',
    duelModeHelp:
      'Swipe mode shows both items side by side.drag a card up to pick it.',
    timeFormatLabel: 'Time format',
    timeFormat12h: '12-hour (1:30 PM)',
    timeFormat24h: '24-hour (13:30)',
    timeFormatHelp: 'Affects how clock times are shown across the app.',
    remindersHeading: 'Duel reminders',
    remindersHelp:
      'Get a friendly nudge to play a duel.keeps your rankings fresh over time.',
    remindersOpenLink: 'Configure reminders',
    remindersStatusOff: 'Off',
    remindersStatusActive: (cadenceLabel: string, timeLabel: string) =>
      `${cadenceLabel} · ${timeLabel}`,
    remindersEnabledLabel: 'Enable reminders',
    remindersCadenceLabel: 'How often',
    remindersCadenceOff: 'Off',
    remindersCadenceDaily: 'Daily',
    remindersCadenceWeekly: 'Weekly',
    remindersCadenceMonthly: 'Monthly',
    remindersCadenceCustom: 'Custom',
    remindersCustomCountLabel: 'How many',
    remindersUnitDay: 'per day',
    remindersUnitWeek: 'per week',
    remindersUnitMonth: 'per month',
    remindersUnitYear: 'per year',
    remindersPreferredHourLabel: 'Preferred time',
    remindersPreferredHourMorning: (time: string) => `Morning · ${time}`,
    remindersPreferredHourMidday: (time: string) => `Midday · ${time}`,
    remindersPreferredHourEvening: (time: string) => `Evening · ${time}`,
    remindersPreferredHourNight: (time: string) => `Night · ${time}`,
    remindersPreferredHourCustom: 'Custom',
    remindersPreferredTimeCustomLabel: 'Pick a time',
    remindersPreferredCurrent: (time: string) => `Currently: ${time}`,
    remindersQuietHoursToggleLabel: 'Quiet hours',
    remindersQuietHoursLabel: 'Quiet hours window',
    remindersQuietHoursHelp: 'No reminders during this window.',
    remindersChannelLabel: 'Where to show reminders',
    remindersChannelInApp: 'In the app only',
    remindersChannelOs: 'OS notifications only',
    remindersChannelBoth: 'Both',
    remindersOsUnsupported:
      'OS notifications are limited on this device.in-app reminders still work.',
    remindersPermissionGranted: 'Notifications enabled.',
    remindersPermissionDenied:
      'Notifications are blocked. Open your browser site settings to allow them, then come back.',
    remindersPermissionDefault:
      'Allow notifications so DuelList can nudge you when the app is in the background.',
    remindersPermissionEnableButton: 'Enable notifications',
    remindersTriggerUnsupportedHelp:
      'Background scheduling isn’t supported on this browser.reminders will only fire while DuelList is open.',
    osNotificationTitle: 'Time for a duel?',
    osNotificationBody: (listName: string, days: number) =>
      days <= 0
        ? `Rank one duel for "${listName}".`
        : `Rank one duel for "${listName}".last played ${days} ${days === 1 ? 'day' : 'days'} ago.`,
    remindersPerListHeading: 'Skip these lists',
    remindersPerListHelp: 'Lists you don’t want reminders for.',
    remindersPerListReminding: 'Reminding',
    remindersPerListSkipped: 'Skipped',
    remindersPerListItemsCount: (n: number) => `${n} ${n === 1 ? 'item' : 'items'}`,
    remindersTestButton: 'Send test reminder',
    remindersTestHelp:
      'Sends a test through your selected channel.in-app banner, OS notification, or both.',
    remindersBack: 'Back to settings',
    aboutHeading: 'About',
    whatsInDuelList: "What's in DuelList",
    replayOnboarding: 'Replay onboarding',
    exportHeading: 'Export',
    storageHeading: 'Storage',
    storageUsage: (usedKb: number, limitMb: number) =>
      `${usedKb.toFixed(1)} KB used of ~${limitMb.toFixed(0)} MB`,
    fileSyncHeading: 'File sync',
    fileSyncLinked: 'Linked.changes sync to file automatically.',
    fileSyncLost: 'File sync lost.permission denied. Re-link to restore.',
    unlinkFile: 'Unlink file',
    linkFile: 'Link to file',
    removedItemsButton: (n: number) => `Removed items (${n})`,
    removedItemsTitle: 'Removed items',
    noRemovedItems: 'No removed items.',
    restoreAria: (name: string) => `Restore ${name}`,
    dangerZone: 'Danger zone',
    deleteList: 'Delete list',
    deleteListConfirm: (name: string) =>
      `Permanently delete "${name}" and all its history? This cannot be undone.`,
  },

  export: {
    exportList: 'Export list',
    exportHistory: 'Export history',
    exportAll: 'Export all lists',
    listButton: 'List (.md)',
    historyButton: 'History (.md)',
    exportAppData: 'Export app data',
  },

  import: {
    conflict: {
      title: 'List already exists',
      message:
        'A list named "{existing}" already exists with the same ID as "{incoming}". Replace it, or import as a new list?',
      replace: 'Replace existing',
      importAsNew: 'Import as new',
      cancel: 'Cancel',
    },
  },

  features: {
    heading: 'Features',
    intro:
      "DuelList turns the painful job of ranking a long list into a stream of easy two-way choices. Here's what's in the box.",
    goToLists: 'Go to your lists',
    list: [
      {
        title: 'Pairwise duels',
        body:
          'No need to rank a long list from scratch. Decide between just two items at a time and the algorithm sorts the rest.',
      },
      {
        title: 'ELO ratings under the hood',
        body:
          'Every choice updates an ELO score. See your list converge with each duel.toggle between rank position and raw ELO from the rankings screen.',
      },
      {
        title: 'Smart pairing',
        body:
          'Pairs are picked to maximize information: similar ratings first, low-confidence items prioritized, recently skipped pairs penalized.',
      },
      {
        title: 'Multiple lists, custom order',
        body:
          'Keep separate lists for movies, snacks, vacation spots.anything. Sort by recent / A–Z / created, or drag to a custom order.',
      },
      {
        title: 'Optional file sync',
        body:
          'On supported browsers, link a list to a Markdown file on your device. Edits stream straight to disk so you can keep your data in version control or sync it via your cloud of choice.',
      },
      {
        title: 'Full duel history',
        body:
          'Every choice is recorded with date and items. Browse the history from the rankings header or export it as Markdown.',
      },
      {
        title: 'Markdown import & export',
        body:
          'Lists are plain Markdown.readable, diffable, portable. Export anytime; import to merge or replace.',
      },
      {
        title: 'Touch-friendly PWA',
        body:
          'Install to your home screen and use offline. Side-by-side and swipe duel modes are tuned for one-handed phone use.',
      },
      {
        title: 'Local-first, private',
        body:
          'No accounts, no servers, no telemetry. Everything is stored in your browser (and optionally your file system). You own your data.',
      },
      {
        title: 'Templates to start fast',
        body:
          'Pick a starter template (Anime, Pizza Toppings, Movies, Vacation, Snacks, Hobbies) when creating a list to skip the empty-state.',
      },
      {
        title: 'Smart reminders',
        body:
          'Choose a cadence (daily, weekly, monthly, custom) and DuelList nudges you about a list that’s gone stale. In-app banner while the app is open, OS notification when it isn’t. Quiet hours and per-list opt-outs are honored.',
      },
    ],
  },
} as const;
