/**
 * UI string accessor.all user-visible text flows through `S`.
 *
 * Backed by i18next. The shape mirrors the en/nl resource trees in
 * `src/locales/`. Leaves are either getters that resolve to the active
 * locale's string at access time, or functions that interpolate named
 * placeholders. Plurals delegate to i18next's CLDR `_one`/`_other`
 * suffix resolution via the `count` option.
 *
 * On locale change, `LocaleProvider` re-mounts the React tree, so every
 * `S.*` access re-resolves automatically. No `useTranslation()` hook
 * needed at call sites.
 */
import i18n from './i18n';

const t = (key: string, opts?: Record<string, unknown>): string =>
  i18n.t(key, opts) as string;

export const S = {
  app: {
    get name() { return t('app.name'); },
    get tagline() { return t('app.tagline'); },
    get storageAlmostFull() { return t('app.storageAlmostFull'); },
    get appSettingsAria() { return t('app.appSettingsAria'); },
    get goBackAria() { return t('app.goBackAria'); },
    get errorBoundaryTitle() { return t('app.errorBoundaryTitle'); },
    get errorBoundaryDescription() { return t('app.errorBoundaryDescription'); },
    get errorBoundaryReload() { return t('app.errorBoundaryReload'); },
    get errorBoundaryDetails() { return t('app.errorBoundaryDetails'); },
    get errorBoundaryCopy() { return t('app.errorBoundaryCopy'); },
    get errorBoundaryCopied() { return t('app.errorBoundaryCopied'); },
    get footerNavAria() { return t('app.footerNavAria'); },
    get footerGlossary() { return t('app.footerGlossary'); },
    get footerTemplates() { return t('app.footerTemplates'); },
    get footerFeatures() { return t('app.footerFeatures'); },
    get footerSettings() { return t('app.footerSettings'); },
    footerVersion: (v: string) => t('app.footerVersion', { v }),
    themeToggleAria: (current: string, next: string) =>
      t('app.themeToggleAria', { current, next }),
  },

  common: {
    get listNotFound() { return t('common.listNotFound'); },
    get pageNotFound() { return t('common.pageNotFound'); },
    get pageNotFoundDescription() { return t('common.pageNotFoundDescription'); },
    get goHome() { return t('common.goHome'); },
    get goToHome() { return t('common.goToHome'); },
    get back() { return t('common.back'); },
    get backToList() { return t('common.backToList'); },
    get backAria() { return t('common.backAria'); },
    get export() { return t('common.export'); },
    get clear() { return t('common.clear'); },
    get clearFilter() { return t('common.clearFilter'); },
    get cancel() { return t('common.cancel'); },
    get add() { return t('common.add'); },
    get next() { return t('common.next'); },
    get create() { return t('common.create'); },
    get delete() { return t('common.delete'); },
    get remove() { return t('common.remove'); },
    get save() { return t('common.save'); },
    get confirmRename() { return t('common.confirmRename'); },
    get saveName() { return t('common.saveName'); },
    get editName() { return t('common.editName'); },
    helpAria: (term: string) => t('common.helpAria', { term }),
  },

  home: {
    get emptyTitle() { return t('home.emptyTitle'); },
    get emptyDescription() { return t('home.emptyDescription'); },
    get createList() { return t('home.createList'); },
    get importList() { return t('home.importList'); },
    get openFile() { return t('home.openFile'); },
    get open() { return t('home.open'); },
    get new() { return t('home.new'); },
    get reorder() { return t('home.reorder'); },
    get done() { return t('home.done'); },
    get sortLabel() { return t('home.sortLabel'); },
    get sortBy() { return t('home.sortBy'); },
    get sortRecent() { return t('home.sortRecent'); },
    get sortAZ() { return t('home.sortAZ'); },
    get sortCreated() { return t('home.sortCreated'); },
    get sortCustom() { return t('home.sortCustom'); },
    get sortFieldRecent() { return t('home.sortFieldRecent'); },
    get sortFieldName() { return t('home.sortFieldName'); },
    get sortFieldCreated() { return t('home.sortFieldCreated'); },
    get sortFieldCustom() { return t('home.sortFieldCustom'); },
    get sortDirAriaRecentDesc() { return t('home.sortDirAriaRecentDesc'); },
    get sortDirAriaRecentAsc() { return t('home.sortDirAriaRecentAsc'); },
    get sortDirAriaNameAsc() { return t('home.sortDirAriaNameAsc'); },
    get sortDirAriaNameDesc() { return t('home.sortDirAriaNameDesc'); },
    get sortDirAriaCreatedDesc() { return t('home.sortDirAriaCreatedDesc'); },
    get sortDirAriaCreatedAsc() { return t('home.sortDirAriaCreatedAsc'); },
    get heroTitle() { return t('home.heroTitle'); },
    get heroSubtitle() { return t('home.heroSubtitle'); },
    get heroAction() { return t('home.heroAction'); },
    get heroNoneEligibleHint() { return t('home.heroNoneEligibleHint'); },
  },

  welcome: {
    get heading() { return t('welcome.heading'); },
    get description() { return t('welcome.description'); },
    get getStarted() { return t('welcome.getStarted'); },
    get trySample() { return t('welcome.trySample'); },
    get skipTour() { return t('welcome.skipTour'); },
    get seeAllFeatures() { return t('welcome.seeAllFeatures'); },
    get seeGlossary() { return t('welcome.seeGlossary'); },
    stepAria: (n: number) => t('welcome.stepAria', { n }),
    get duelStepTitle() { return t('welcome.duelStepTitle'); },
    get duelStepDescription() { return t('welcome.duelStepDescription'); },
    get sessionsStepTitle() { return t('welcome.sessionsStepTitle'); },
    get sessionsStepDescription() { return t('welcome.sessionsStepDescription'); },
    get loopStepTitle() { return t('welcome.loopStepTitle'); },
    get loopStepDescription() { return t('welcome.loopStepDescription'); },
    get templatesStepTitle() { return t('welcome.templatesStepTitle'); },
    get templatesStepDescription() { return t('welcome.templatesStepDescription'); },
    get readyStepTitle() { return t('welcome.readyStepTitle'); },
    get readyStepDescription() { return t('welcome.readyStepDescription'); },
    get step0Alt() { return t('welcome.step0Alt'); },
    get step1Alt() { return t('welcome.step1Alt'); },
    get step2Alt() { return t('welcome.step2Alt'); },
    get step3Alt() { return t('welcome.step3Alt'); },
    get step4Alt() { return t('welcome.step4Alt'); },
    get step5Alt() { return t('welcome.step5Alt'); },
  },

  duel: {
    get skipLabel() { return t('duel.skipLabel'); },
    get sessionComplete() { return t('duel.sessionComplete'); },
    get needTwoItems() { return t('duel.needTwoItems'); },
    get tie() { return t('duel.tie'); },
    get skip() { return t('duel.skip'); },
    duelsCompleted: (n: number) => t('duel.duelsCompleted', { count: n }),
    get currentTop3() { return t('duel.currentTop3'); },
    get biggestMovers() { return t('duel.biggestMovers'); },
    get rankings() { return t('duel.rankings'); },
    get newSession() { return t('duel.newSession'); },
    get undo() { return t('duel.undo'); },
    get undoAria() { return t('duel.undoAria'); },
    get addItems() { return t('duel.addItems'); },
    get endSession() { return t('duel.endSession'); },
    get endShort() { return t('duel.endShort'); },
    get finalDuel() { return t('duel.finalDuel'); },
    get finalDuelAnnouncement() { return t('duel.finalDuelAnnouncement'); },
    get viewHistory() { return t('duel.viewHistory'); },
    needTwoItemsWithCount: (have: number, need: number) =>
      t('duel.needTwoItemsWithCount', { have, need, count: have }),
    get keyboardHintAria() { return t('duel.keyboardHintAria'); },
    pairAnnouncement: (round: number, a: string, b: string) =>
      t('duel.pairAnnouncement', { round, a, b }),
    get newSessionConfirmTitle() { return t('duel.newSessionConfirmTitle'); },
    get newSessionConfirmMessage() { return t('duel.newSessionConfirmMessage'); },
    get newSessionConfirmButton() { return t('duel.newSessionConfirmButton'); },
    get keyboardHint() { return t('duel.keyboardHint'); },
    get comingSoonTitle() { return t('duel.comingSoonTitle'); },
    comingSoonMessage: (modeName: string) => t('duel.comingSoonMessage', { modeName }),
    get startSideBySideInstead() { return t('duel.startSideBySideInstead'); },
    pickAria: (name: string) => t('duel.pickAria', { name }),
    get pickBadge() { return t('duel.pickBadge'); },
    scoreSuffix: (n: number) => t('duel.scoreSuffix', { count: n }),
  },

  ranking: {
    get addItemsPrompt() { return t('ranking.addItemsPrompt'); },
    get startComparing() { return t('ranking.startComparing'); },
    get startDuel() { return t('ranking.startDuel'); },
    get heroSubtitle() { return t('ranking.heroSubtitle'); },
    get rank() { return t('ranking.rank'); },
    get score() { return t('ranking.score'); },
    get rankTooltip() { return t('ranking.rankTooltip'); },
    get scoreTooltip() { return t('ranking.scoreTooltip'); },
    duelsPlayed: (n: number) => t('ranking.duelsPlayed', { count: n }),
    get switchToRank() { return t('ranking.switchToRank'); },
    get switchToScore() { return t('ranking.switchToScore'); },
    get addItems() { return t('ranking.addItems'); },
    get historyAria() { return t('ranking.historyAria'); },
    get addItemsAria() { return t('ranking.addItemsAria'); },
    get settingsAria() { return t('ranking.settingsAria'); },
    get fileLinked() { return t('ranking.fileLinked'); },
    get fileLinkedTooltip() { return t('ranking.fileLinkedTooltip'); },
    get fileLinkBroken() { return t('ranking.fileLinkBroken'); },
    get fileLinkBrokenTooltip() { return t('ranking.fileLinkBrokenTooltip'); },
    get fileNotLinked() { return t('ranking.fileNotLinked'); },
    get fileNotLinkedTooltip() { return t('ranking.fileNotLinkedTooltip'); },
    get linkFileConfirmTitle() { return t('ranking.linkFileConfirmTitle'); },
    get linkFileConfirmMessage() { return t('ranking.linkFileConfirmMessage'); },
    get relinkFileConfirmMessage() { return t('ranking.relinkFileConfirmMessage'); },
    optionsAria: (name: string) => t('ranking.optionsAria', { name }),
    renameAria: (name: string) => t('ranking.renameAria', { name }),
    get renameAction() { return t('ranking.renameAction'); },
    get removeAction() { return t('ranking.removeAction'); },
    get detailsAction() { return t('ranking.detailsAction'); },
    get removeItemTitle() { return t('ranking.removeItemTitle'); },
    removeItemMessage: (name: string) => t('ranking.removeItemMessage', { name }),
    removedHeading: (n: number) => t('ranking.removedHeading', { count: n }),
    get removedExpandAria() { return t('ranking.removedExpandAria'); },
    get removedCollapseAria() { return t('ranking.removedCollapseAria'); },
    restoreItemAria: (name: string) => t('ranking.restoreItemAria', { name }),
    get restoreAction() { return t('ranking.restoreAction'); },
    removedItemMeta: (elo: number, duels: number) =>
      t('ranking.removedItemMeta', { elo: Math.round(elo), count: duels }),
    get filterPlaceholder() { return t('ranking.filterPlaceholder'); },
    get filterAria() { return t('ranking.filterAria'); },
    noMatch: (query: string) => t('ranking.noMatch', { query }),
    get restoreKeepsStatsHint() { return t('ranking.restoreKeepsStatsHint'); },
    movedUp: (n: number) => t('ranking.movedUp', { count: n }),
    movedDown: (n: number) => t('ranking.movedDown', { count: n }),
    get noChange() { return t('ranking.noChange'); },
    topItemPrefix: (name: string) => t('ranking.topItemPrefix', { name }),
    itemsCount: (n: number) => t('ranking.itemsCount', { count: n }),
    get sortLabel() { return t('ranking.sortLabel'); },
    get sortRankDesc() { return t('ranking.sortRankDesc'); },
    get sortRankAsc() { return t('ranking.sortRankAsc'); },
    get sortScoreDesc() { return t('ranking.sortScoreDesc'); },
    get sortScoreAsc() { return t('ranking.sortScoreAsc'); },
    get sortAddedDesc() { return t('ranking.sortAddedDesc'); },
    get sortAddedAsc() { return t('ranking.sortAddedAsc'); },
    get sortNameAsc() { return t('ranking.sortNameAsc'); },
    get sortNameDesc() { return t('ranking.sortNameDesc'); },
    get sortFieldRank() { return t('ranking.sortFieldRank'); },
    get sortFieldScore() { return t('ranking.sortFieldScore'); },
    get sortFieldAdded() { return t('ranking.sortFieldAdded'); },
    get sortFieldName() { return t('ranking.sortFieldName'); },
    get sortDirAriaRankDesc() { return t('ranking.sortDirAriaRankDesc'); },
    get sortDirAriaRankAsc() { return t('ranking.sortDirAriaRankAsc'); },
    get sortDirAriaScoreDesc() { return t('ranking.sortDirAriaScoreDesc'); },
    get sortDirAriaScoreAsc() { return t('ranking.sortDirAriaScoreAsc'); },
    get sortDirAriaAddedDesc() { return t('ranking.sortDirAriaAddedDesc'); },
    get sortDirAriaAddedAsc() { return t('ranking.sortDirAriaAddedAsc'); },
    get sortDirAriaNameAsc() { return t('ranking.sortDirAriaNameAsc'); },
    get sortDirAriaNameDesc() { return t('ranking.sortDirAriaNameDesc'); },
    get detailsTitle() { return t('ranking.detailsTitle'); },
    get detailsRank() { return t('ranking.detailsRank'); },
    get detailsScore() { return t('ranking.detailsScore'); },
    get detailsAdded() { return t('ranking.detailsAdded'); },
    get detailsLastDuel() { return t('ranking.detailsLastDuel'); },
    get detailsNever() { return t('ranking.detailsNever'); },
    get detailsWins() { return t('ranking.detailsWins'); },
    get detailsLosses() { return t('ranking.detailsLosses'); },
    get detailsTies() { return t('ranking.detailsTies'); },
    get detailsTotal() { return t('ranking.detailsTotal'); },
    get detailsNotesLabel() { return t('ranking.detailsNotesLabel'); },
    get detailsNotesPlaceholder() { return t('ranking.detailsNotesPlaceholder'); },
    get detailsNoNotes() { return t('ranking.detailsNoNotes'); },
    get detailsLastDuels() { return t('ranking.detailsLastDuels'); },
    get detailsNoDuelsYet() { return t('ranking.detailsNoDuelsYet'); },
    get detailsViewAllDuels() { return t('ranking.detailsViewAllDuels'); },
    get detailsOutcomeWin() { return t('ranking.detailsOutcomeWin'); },
    get detailsOutcomeLoss() { return t('ranking.detailsOutcomeLoss'); },
    get detailsOutcomeTie() { return t('ranking.detailsOutcomeTie'); },
    hasNotesAria: (name: string) => t('ranking.hasNotesAria', { name }),
    openDetailsAria: (name: string) => t('ranking.openDetailsAria', { name }),
  },

  itemDetail: {
    get notFound() { return t('itemDetail.notFound'); },
    get backToList() { return t('itemDetail.backToList'); },
    renameAria: (name: string) => t('itemDetail.renameAria', { name }),
    get removeButton() { return t('itemDetail.removeButton'); },
    get winRate() { return t('itemDetail.winRate'); },
    get record() { return t('itemDetail.record'); },
    get rivalriesHeading() { return t('itemDetail.rivalriesHeading'); },
    get biggestRival() { return t('itemDetail.biggestRival'); },
    get mostWinsAgainst() { return t('itemDetail.mostWinsAgainst'); },
    get lostMostTo() { return t('itemDetail.lostMostTo'); },
    get noRivalsYet() { return t('itemDetail.noRivalsYet'); },
    opponentRecord: (w: number, l: number, ties: number) =>
      t('itemDetail.opponentRecord', { w, l, t: ties }),
    opponentTotalAria: (n: number) => t('itemDetail.opponentTotalAria', { count: n }),
    trendUp: (n: number) => t('itemDetail.trendUp', { count: n }),
    trendDown: (n: number) => t('itemDetail.trendDown', { count: n }),
    get notesUnsaved() { return t('itemDetail.notesUnsaved'); },
    get notesSaving() { return t('itemDetail.notesSaving'); },
    get notesSaved() { return t('itemDetail.notesSaved'); },
    editedRelative: (rel: string) => t('itemDetail.editedRelative', { rel }),
    notesEditedRelative: (rel: string) => t('itemDetail.notesEditedRelative', { rel }),
    charsCount: (n: number) => t('itemDetail.charsCount', { count: n }),
    wordsCount: (n: number) => t('itemDetail.wordsCount', { count: n }),
    get recentFormHeading() { return t('itemDetail.recentFormHeading'); },
    recentOutcomeWinAria: (name: string) => t('itemDetail.recentOutcomeWinAria', { name }),
    recentOutcomeLossAria: (name: string) => t('itemDetail.recentOutcomeLossAria', { name }),
    recentOutcomeTieAria: (name: string) => t('itemDetail.recentOutcomeTieAria', { name }),
    percentileLine: (pct: number, total: number) =>
      t('itemDetail.percentileLine', { pct, total }),
    coverageLine: (seen: number, possible: number) =>
      t('itemDetail.coverageLine', { seen, count: possible }),
    winStreak: (n: number) => t('itemDetail.winStreak', { count: n }),
    lossStreak: (n: number) => t('itemDetail.lossStreak', { count: n }),
  },

  list: {
    get deleteConfirm() { return t('list.deleteConfirm'); },
    get noItems() { return t('list.noItems'); },
    get name() { return t('list.name'); },
    get addItemsTitle() { return t('list.addItemsTitle'); },
    get addItemsHelp() { return t('list.addItemsHelp'); },
    get addItemsPlaceholder() { return t('list.addItemsPlaceholder'); },
    get namePlaceholder() { return t('list.namePlaceholder'); },
    templateItemCount: (n: number) => t('list.templateItemCount', { count: n }),
    get quickStartHeading() { return t('list.quickStartHeading'); },
    get quickStartDesc() { return t('list.quickStartDesc'); },
    get neverOpened() { return t('list.neverOpened'); },
    get notLinkedShort() { return t('list.notLinkedShort'); },
    get filterPlaceholder() { return t('list.filterPlaceholder'); },
    get filterAria() { return t('list.filterAria'); },
    noMatch: (query: string) => t('list.noMatch', { query }),
    get justNow() { return t('list.justNow'); },
    minutesAgo: (n: number) => t('list.minutesAgo', { count: n }),
    hoursAgo: (n: number) => t('list.hoursAgo', { count: n }),
    get yesterday() { return t('list.yesterday'); },
    daysAgo: (n: number) => t('list.daysAgo', { count: n }),
    draggableAria: (name: string) => t('list.draggableAria', { name }),
    dragAria: (name: string) => t('list.dragAria', { name }),
    moveUpAria: (name: string) => t('list.moveUpAria', { name }),
    moveDownAria: (name: string) => t('list.moveDownAria', { name }),
    duelsCount: (n: number) => t('list.duelsCount', { count: n }),
    addMoreItemsCta: (n: number) => t('list.addMoreItemsCta', { count: n }),
    get noDuelsYet() { return t('list.noDuelsYet'); },
    get activityFresh() { return t('list.activityFresh'); },
    get activityStale() { return t('list.activityStale'); },
    get activityCold() { return t('list.activityCold'); },
    get activityNever() { return t('list.activityNever'); },
    podiumPositionAria: (pos: number, name: string) =>
      t('list.podiumPositionAria', { pos, name }),
    quickDuelAria: (name: string) => t('list.quickDuelAria', { name }),
  },

  glossary: {
    get heading() { return t('glossary.heading'); },
    get intro() { return t('glossary.intro'); },
    get backAria() { return t('glossary.backAria'); },
    get openLink() { return t('glossary.openLink'); },
    get sectionTerminology() { return t('glossary.sectionTerminology'); },
    get termListLabel() { return t('glossary.termListLabel'); },
    get termListDesc() { return t('glossary.termListDesc'); },
    get termItemLabel() { return t('glossary.termItemLabel'); },
    get termItemDesc() { return t('glossary.termItemDesc'); },
    get termItemListLabel() { return t('glossary.termItemListLabel'); },
    get termItemListDesc() { return t('glossary.termItemListDesc'); },
    get termDuelLabel() { return t('glossary.termDuelLabel'); },
    get termDuelDesc() { return t('glossary.termDuelDesc'); },
    get termSessionLabel() { return t('glossary.termSessionLabel'); },
    get termSessionDesc() { return t('glossary.termSessionDesc'); },
    get termScoreLabel() { return t('glossary.termScoreLabel'); },
    get termScoreDesc() { return t('glossary.termScoreDesc'); },
    get termRankLabel() { return t('glossary.termRankLabel'); },
    get termRankDesc() { return t('glossary.termRankDesc'); },
    get termBrandLabel() { return t('glossary.termBrandLabel'); },
    get termBrandDesc() { return t('glossary.termBrandDesc'); },
    get termReminderLabel() { return t('glossary.termReminderLabel'); },
    get termReminderDesc() { return t('glossary.termReminderDesc'); },
    get termCadenceLabel() { return t('glossary.termCadenceLabel'); },
    get termCadenceDesc() { return t('glossary.termCadenceDesc'); },
    get termQuietHoursLabel() { return t('glossary.termQuietHoursLabel'); },
    get termQuietHoursDesc() { return t('glossary.termQuietHoursDesc'); },
    get termSnoozeLabel() { return t('glossary.termSnoozeLabel'); },
    get termSnoozeDesc() { return t('glossary.termSnoozeDesc'); },
    get termTieLabel() { return t('glossary.termTieLabel'); },
    get termTieDesc() { return t('glossary.termTieDesc'); },
    get termSkipLabel() { return t('glossary.termSkipLabel'); },
    get termSkipDesc() { return t('glossary.termSkipDesc'); },
    get termTemplateLabel() { return t('glossary.termTemplateLabel'); },
    get termTemplateDesc() { return t('glossary.termTemplateDesc'); },
    get termThemeLabel() { return t('glossary.termThemeLabel'); },
    get termThemeDesc() { return t('glossary.termThemeDesc'); },
    get termRankingSpeedLabel() { return t('glossary.termRankingSpeedLabel'); },
    get termRankingSpeedDesc() { return t('glossary.termRankingSpeedDesc'); },
    get termDefaultsLabel() { return t('glossary.termDefaultsLabel'); },
    get termDefaultsDesc() { return t('glossary.termDefaultsDesc'); },
    get sectionActivity() { return t('glossary.sectionActivity'); },
    get sectionFileLink() { return t('glossary.sectionFileLink'); },
    get sectionRankingView() { return t('glossary.sectionRankingView'); },
    get sectionQuickActions() { return t('glossary.sectionQuickActions'); },
    get sectionTrend() { return t('glossary.sectionTrend'); },
    get sectionCardStates() { return t('glossary.sectionCardStates'); },
    get sectionReminder() { return t('glossary.sectionReminder'); },
    get sectionRemoved() { return t('glossary.sectionRemoved'); },
    get activityFreshDesc() { return t('glossary.activityFreshDesc'); },
    get activityStaleDesc() { return t('glossary.activityStaleDesc'); },
    get activityColdDesc() { return t('glossary.activityColdDesc'); },
    get activityNeverDesc() { return t('glossary.activityNeverDesc'); },
    get fileLinkedLabel() { return t('glossary.fileLinkedLabel'); },
    get fileLinkedDesc() { return t('glossary.fileLinkedDesc'); },
    get fileBrokenLabel() { return t('glossary.fileBrokenLabel'); },
    get fileBrokenDesc() { return t('glossary.fileBrokenDesc'); },
    get fileNotLinkedLabel() { return t('glossary.fileNotLinkedLabel'); },
    get fileNotLinkedDesc() { return t('glossary.fileNotLinkedDesc'); },
    get rankViewLabel() { return t('glossary.rankViewLabel'); },
    get rankViewDesc() { return t('glossary.rankViewDesc'); },
    get scoreViewLabel() { return t('glossary.scoreViewLabel'); },
    get scoreViewDesc() { return t('glossary.scoreViewDesc'); },
    get actionHistoryLabel() { return t('glossary.actionHistoryLabel'); },
    get actionHistoryDesc() { return t('glossary.actionHistoryDesc'); },
    get actionAddLabel() { return t('glossary.actionAddLabel'); },
    get actionAddDesc() { return t('glossary.actionAddDesc'); },
    get actionSettingsLabel() { return t('glossary.actionSettingsLabel'); },
    get actionSettingsDesc() { return t('glossary.actionSettingsDesc'); },
    get trendUpLabel() { return t('glossary.trendUpLabel'); },
    get trendUpDesc() { return t('glossary.trendUpDesc'); },
    get trendDownLabel() { return t('glossary.trendDownLabel'); },
    get trendDownDesc() { return t('glossary.trendDownDesc'); },
    get cardCtaAddLabel() { return t('glossary.cardCtaAddLabel'); },
    get cardCtaAddDesc() { return t('glossary.cardCtaAddDesc'); },
    get cardCtaNoDuelsLabel() { return t('glossary.cardCtaNoDuelsLabel'); },
    get cardCtaNoDuelsDesc() { return t('glossary.cardCtaNoDuelsDesc'); },
    get cardPodiumLabel() { return t('glossary.cardPodiumLabel'); },
    get cardPodiumDesc() { return t('glossary.cardPodiumDesc'); },
    get reminderBellLabel() { return t('glossary.reminderBellLabel'); },
    get reminderBellDesc() { return t('glossary.reminderBellDesc'); },
    get reminderSwordsLabel() { return t('glossary.reminderSwordsLabel'); },
    get reminderSwordsDesc() { return t('glossary.reminderSwordsDesc'); },
    get removedLabel() { return t('glossary.removedLabel'); },
    get removedDesc() { return t('glossary.removedDesc'); },
  },

  reminders: {
    get bannerTitle() { return t('reminders.bannerTitle'); },
    bannerSubtitle: (listName: string, days: number) =>
      days <= 0
        ? t('reminders.bannerSubtitleToday', { listName })
        : t('reminders.bannerSubtitle', { listName, count: days }),
    get play() { return t('reminders.play'); },
    get snooze() { return t('reminders.snooze'); },
    get skip() { return t('reminders.skip'); },
    get dismissAria() { return t('reminders.dismissAria'); },
  },

  history: {
    get title() { return t('history.title'); },
    get emptyDescription() { return t('history.emptyDescription'); },
    get startDuel() { return t('history.startDuel'); },
    get statTotal() { return t('history.statTotal'); },
    get statTies() { return t('history.statTies'); },
    get statTopWinner() { return t('history.statTopWinner'); },
    get statBiggestRivalry() { return t('history.statBiggestRivalry'); },
    get sparklineRangeLabel() { return t('history.sparklineRangeLabel'); },
    get sparklineAria() { return t('history.sparklineAria'); },
    get filterPlaceholder() { return t('history.filterPlaceholder'); },
    get filterAria() { return t('history.filterAria'); },
    noMatch: (query: string) => t('history.noMatch', { query }),
    showingOf: (shown: number, total: number) =>
      t('history.showingOf', { shown, count: total }),
    totalDuels: (n: number) => t('history.totalDuels', { count: n }),
    winsCount: (n: number) => t('history.winsCount', { count: n }),
    meetingsCount: (n: number) => t('history.meetingsCount', { count: n }),
    sparklineDay: (date: string, n: number) =>
      t('history.sparklineDay', { date, count: n }),
    get statMostOneSided() { return t('history.statMostOneSided'); },
    get statLongestStreak() { return t('history.statLongestStreak'); },
    get statMatchupCoverage() { return t('history.statMatchupCoverage'); },
    get statMostActiveDay() { return t('history.statMostActiveDay'); },
    coverageValue: (seen: number, total: number) =>
      t('history.coverageValue', { seen, total }),
    streakWins: (n: number) => t('history.streakWins', { count: n }),
    get streakHelp() { return t('history.streakHelp'); },
    get oneSidedHelp() { return t('history.oneSidedHelp'); },
    get coverageHelp() { return t('history.coverageHelp'); },
    duelsOnDay: (n: number) => t('history.duelsOnDay', { count: n }),
    oneSidedRecord: (wins: number, losses: number) =>
      t('history.oneSidedRecord', { wins, losses }),
    get vsBadge() { return t('history.vsBadge'); },
    get tieBadge() { return t('history.tieBadge'); },
    get versusAria() { return t('history.versusAria'); },
    get tieAria() { return t('history.tieAria'); },
    get winnerAria() { return t('history.winnerAria'); },
    get exportHistoryAria() { return t('history.exportHistoryAria'); },
  },

  settings: {
    get title() { return t('settings.title'); },
    get kFactorLabel() { return t('settings.kFactorLabel'); },
    get kFactorQuick() { return t('settings.kFactorQuick'); },
    get kFactorGradual() { return t('settings.kFactorGradual'); },
    get kFactorTight() { return t('settings.kFactorTight'); },
    get kFactorHelp() { return t('settings.kFactorHelp'); },
    get kFactorTooltipQuick() { return t('settings.kFactorTooltipQuick'); },
    get kFactorTooltipGradual() { return t('settings.kFactorTooltipGradual'); },
    get kFactorTooltipTight() { return t('settings.kFactorTooltipTight'); },
    get sessionLengthLabel() { return t('settings.sessionLengthLabel'); },
    get sessionLengthUnit() { return t('settings.sessionLengthUnit'); },
    get sessionLengthUnlimited() { return t('settings.sessionLengthUnlimited'); },
    get sessionLengthCustom() { return t('settings.sessionLengthCustom'); },
    get sessionLengthHelp() { return t('settings.sessionLengthHelp'); },
    get defaultsHeading() { return t('settings.defaultsHeading'); },
    get defaultsOpenLink() { return t('settings.defaultsOpenLink'); },
    get defaultsTitle() { return t('settings.defaultsTitle'); },
    get defaultsSubtitle() { return t('settings.defaultsSubtitle'); },
    get defaultsKFactorHelp() { return t('settings.defaultsKFactorHelp'); },
    get defaultsSessionHelp() { return t('settings.defaultsSessionHelp'); },
    get applyToAllLists() { return t('settings.applyToAllLists'); },
    get applyKFactorConfirmTitle() { return t('settings.applyKFactorConfirmTitle'); },
    applyKFactorConfirmMessage: (label: string, count: number) =>
      t('settings.applyKFactorConfirmMessage', { label, count }),
    get applySessionConfirmTitle() { return t('settings.applySessionConfirmTitle'); },
    applySessionConfirmMessage: (label: string, count: number) =>
      t('settings.applySessionConfirmMessage', { label, count }),
    get applyConfirmButton() { return t('settings.applyConfirmButton'); },
    applySuccess: (count: number) => t('settings.applySuccess', { count }),
    get applyNoChange() { return t('settings.applyNoChange'); },
    get showScoresDuringDuelsLabel() { return t('settings.showScoresDuringDuelsLabel'); },
    get showScoresDuringDuelsDesc() { return t('settings.showScoresDuringDuelsDesc'); },
    get defaultShowScoresDuringDuelsLabel() { return t('settings.defaultShowScoresDuringDuelsLabel'); },
    get defaultShowScoresDuringDuelsDesc() { return t('settings.defaultShowScoresDuringDuelsDesc'); },
    get applyShowScoresConfirmTitle() { return t('settings.applyShowScoresConfirmTitle'); },
    applyShowScoresConfirmMessage: (label: string, count: number) =>
      t('settings.applyShowScoresConfirmMessage', { label, count }),
    get showScoresShow() { return t('settings.showScoresShow'); },
    get showScoresHide() { return t('settings.showScoresHide'); },
    get themeLabel() { return t('settings.themeLabel'); },
    get themeSystem() { return t('settings.themeSystem'); },
    get themeLight() { return t('settings.themeLight'); },
    get themeDark() { return t('settings.themeDark'); },
    get languageLabel() { return t('settings.languageLabel'); },
    get languageHelp() { return t('settings.languageHelp'); },
    get languageSystem() { return t('settings.languageSystem'); },
    get languageEnglish() { return t('settings.languageEnglish'); },
    get languageDutch() { return t('settings.languageDutch'); },
    get duelModeLabel() { return t('settings.duelModeLabel'); },
    get duelModeSideBySide() { return t('settings.duelModeSideBySide'); },
    get duelModeSpeedRound() { return t('settings.duelModeSpeedRound'); },
    get duelModeBracket() { return t('settings.duelModeBracket'); },
    get duelModeComingSoonBadge() { return t('settings.duelModeComingSoonBadge'); },
    get duelModeHelp() { return t('settings.duelModeHelp'); },
    get timeFormatLabel() { return t('settings.timeFormatLabel'); },
    get timeFormat12h() { return t('settings.timeFormat12h'); },
    get timeFormat24h() { return t('settings.timeFormat24h'); },
    get timeFormatHelp() { return t('settings.timeFormatHelp'); },
    get remindersHeading() { return t('settings.remindersHeading'); },
    get remindersHelp() { return t('settings.remindersHelp'); },
    get remindersOpenLink() { return t('settings.remindersOpenLink'); },
    get remindersStatusOff() { return t('settings.remindersStatusOff'); },
    remindersStatusActive: (cadenceLabel: string, timeLabel: string) =>
      t('settings.remindersStatusActive', { cadenceLabel, timeLabel }),
    get remindersEnabledLabel() { return t('settings.remindersEnabledLabel'); },
    get remindersCadenceLabel() { return t('settings.remindersCadenceLabel'); },
    get remindersCadenceOff() { return t('settings.remindersCadenceOff'); },
    get remindersCadenceDaily() { return t('settings.remindersCadenceDaily'); },
    get remindersCadenceWeekly() { return t('settings.remindersCadenceWeekly'); },
    get remindersCadenceMonthly() { return t('settings.remindersCadenceMonthly'); },
    get remindersCadenceCustom() { return t('settings.remindersCadenceCustom'); },
    get remindersCustomCountLabel() { return t('settings.remindersCustomCountLabel'); },
    get remindersUnitDay() { return t('settings.remindersUnitDay'); },
    get remindersUnitWeek() { return t('settings.remindersUnitWeek'); },
    get remindersUnitMonth() { return t('settings.remindersUnitMonth'); },
    get remindersUnitYear() { return t('settings.remindersUnitYear'); },
    get remindersPreferredHourLabel() { return t('settings.remindersPreferredHourLabel'); },
    remindersPreferredHourMorning: (time: string) =>
      t('settings.remindersPreferredHourMorning', { time }),
    remindersPreferredHourMidday: (time: string) =>
      t('settings.remindersPreferredHourMidday', { time }),
    remindersPreferredHourEvening: (time: string) =>
      t('settings.remindersPreferredHourEvening', { time }),
    remindersPreferredHourNight: (time: string) =>
      t('settings.remindersPreferredHourNight', { time }),
    get remindersPreferredHourCustom() { return t('settings.remindersPreferredHourCustom'); },
    get remindersPreferredTimeCustomLabel() { return t('settings.remindersPreferredTimeCustomLabel'); },
    remindersPreferredCurrent: (time: string) =>
      t('settings.remindersPreferredCurrent', { time }),
    get remindersQuietHoursToggleLabel() { return t('settings.remindersQuietHoursToggleLabel'); },
    get remindersQuietHoursLabel() { return t('settings.remindersQuietHoursLabel'); },
    get remindersQuietHoursHelp() { return t('settings.remindersQuietHoursHelp'); },
    get remindersChannelLabel() { return t('settings.remindersChannelLabel'); },
    get remindersChannelInApp() { return t('settings.remindersChannelInApp'); },
    get remindersChannelOs() { return t('settings.remindersChannelOs'); },
    get remindersChannelBoth() { return t('settings.remindersChannelBoth'); },
    get remindersOsUnsupported() { return t('settings.remindersOsUnsupported'); },
    get remindersPermissionGranted() { return t('settings.remindersPermissionGranted'); },
    get remindersPermissionDenied() { return t('settings.remindersPermissionDenied'); },
    get remindersPermissionDefault() { return t('settings.remindersPermissionDefault'); },
    get remindersPermissionEnableButton() { return t('settings.remindersPermissionEnableButton'); },
    get remindersTriggerUnsupportedHelp() { return t('settings.remindersTriggerUnsupportedHelp'); },
    get osNotificationTitle() { return t('settings.osNotificationTitle'); },
    osNotificationBody: (listName: string, days: number) =>
      days <= 0
        ? t('settings.osNotificationBodyToday', { listName })
        : t('settings.osNotificationBody', { listName, count: days }),
    get remindersPerListHeading() { return t('settings.remindersPerListHeading'); },
    get remindersPerListHelp() { return t('settings.remindersPerListHelp'); },
    get remindersPerListReminding() { return t('settings.remindersPerListReminding'); },
    get remindersPerListSkipped() { return t('settings.remindersPerListSkipped'); },
    remindersPerListItemsCount: (n: number) =>
      t('settings.remindersPerListItemsCount', { count: n }),
    get remindersTestButton() { return t('settings.remindersTestButton'); },
    get remindersTestHelp() { return t('settings.remindersTestHelp'); },
    get remindersBack() { return t('settings.remindersBack'); },
    get titleApp() { return t('settings.titleApp'); },
    get titleList() { return t('settings.titleList'); },
    get renameButton() { return t('settings.renameButton'); },
    get subheadingExport() { return t('settings.subheadingExport'); },
    get subheadingRecovery() { return t('settings.subheadingRecovery'); },
    get syncIntro() { return t('settings.syncIntro'); },
    get exportListLabel() { return t('settings.exportListLabel'); },
    get exportListDesc() { return t('settings.exportListDesc'); },
    get exportHistoryLabel() { return t('settings.exportHistoryLabel'); },
    get exportHistoryDesc() { return t('settings.exportHistoryDesc'); },
    get groupRanking() { return t('settings.groupRanking'); },
    get groupAppearance() { return t('settings.groupAppearance'); },
    get groupSync() { return t('settings.groupSync'); },
    get groupData() { return t('settings.groupData'); },
    get groupHelp() { return t('settings.groupHelp'); },
    get aboutHeading() { return t('settings.aboutHeading'); },
    get whatsInDuelList() { return t('settings.whatsInDuelList'); },
    get replayOnboarding() { return t('settings.replayOnboarding'); },
    get exportHeading() { return t('settings.exportHeading'); },
    get storageHeading() { return t('settings.storageHeading'); },
    storageUsage: (usedKb: number, limitMb: number) =>
      t('settings.storageUsage', { used: usedKb.toFixed(1), limit: limitMb.toFixed(0) }),
    get fileSyncHeading() { return t('settings.fileSyncHeading'); },
    get fileSyncLinked() { return t('settings.fileSyncLinked'); },
    get fileSyncLost() { return t('settings.fileSyncLost'); },
    get fileSyncUnsupported() { return t('settings.fileSyncUnsupported'); },
    get unlinkFile() { return t('settings.unlinkFile'); },
    get unlinkConfirmTitle() { return t('settings.unlinkConfirmTitle'); },
    get unlinkConfirmMessage() { return t('settings.unlinkConfirmMessage'); },
    get linkFile() { return t('settings.linkFile'); },
    removedItemsButton: (n: number) => t('settings.removedItemsButton', { count: n }),
    get removedItemsTitle() { return t('settings.removedItemsTitle'); },
    get noRemovedItems() { return t('settings.noRemovedItems'); },
    restoreAria: (name: string) => t('settings.restoreAria', { name }),
    get dangerZone() { return t('settings.dangerZone'); },
    get deleteList() { return t('settings.deleteList'); },
    deleteListConfirm: (name: string) => t('settings.deleteListConfirm', { name }),
    get developerHeading() { return t('settings.developerHeading'); },
    get developerHelp() { return t('settings.developerHelp'); },
    get devTriggerError() { return t('settings.devTriggerError'); },
    get devTriggerErrorHelp() { return t('settings.devTriggerErrorHelp'); },
    get devCopyLastError() { return t('settings.devCopyLastError'); },
    get devCopyLastErrorHelp() { return t('settings.devCopyLastErrorHelp'); },
    get devNoErrorYet() { return t('settings.devNoErrorYet'); },
    devLastErrorPreview: (relative: string, message: string) =>
      t('settings.devLastErrorPreview', { relative, message }),
    get devCopied() { return t('settings.devCopied'); },
    get devClearLog() { return t('settings.devClearLog'); },
    get devClearLogHelp() { return t('settings.devClearLogHelp'); },
    get devClearLogConfirm() { return t('settings.devClearLogConfirm'); },
  },

  export: {
    get exportList() { return t('export.exportList'); },
    get exportHistory() { return t('export.exportHistory'); },
    get exportAll() { return t('export.exportAll'); },
    get listButton() { return t('export.listButton'); },
    get historyButton() { return t('export.historyButton'); },
    get exportAppData() { return t('export.exportAppData'); },
  },

  import: {
    conflict: {
      get title() { return t('import.conflict.title'); },
      message: (existing: string, incoming: string) =>
        t('import.conflict.message', { existing, incoming }),
      get replace() { return t('import.conflict.replace'); },
      get importAsNew() { return t('import.conflict.importAsNew'); },
      get cancel() { return t('import.conflict.cancel'); },
    },
  },

  templates: {
    get title() { return t('templates.title'); },
    get subtitle() { return t('templates.subtitle'); },
    itemCount: (n: number) => t('templates.itemCount', { count: n }),
    get showItems() { return t('templates.showItems'); },
    get hideItems() { return t('templates.hideItems'); },
    get createButton() { return t('templates.createButton'); },
    createSuccess: (name: string) => t('templates.createSuccess', { name }),
  },

  features: {
    get heading() { return t('features.heading'); },
    get intro() { return t('features.intro'); },
    get goToLists() { return t('features.goToLists'); },
    get list(): readonly { title: string; body: string }[] {
      return i18n.t('features.list', { returnObjects: true }) as unknown as readonly {
        title: string;
        body: string;
      }[];
    },
  },

  toast: {
    get fileLinkSuccess() { return t('toast.fileLinkSuccess'); },
    get fileUnlinkSuccess() { return t('toast.fileUnlinkSuccess'); },
    get filePermissionDenied() { return t('toast.filePermissionDenied'); },
    get fileNotFound() { return t('toast.fileNotFound'); },
    get fileParseError() { return t('toast.fileParseError'); },
    get fileGenericError() { return t('toast.fileGenericError'); },
    get exportError() { return t('toast.exportError'); },
  },
};
