import { useState } from 'react';
import { Link, useParams, useNavigate } from 'react-router';
import { Button } from '@/components/ui/button';
import { getList, getHistory } from '@/lib/storage';
import { useExport } from '@/hooks/useExport';
import { ArrowLeft, Download } from 'lucide-react';

export default function History() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { exportHistory } = useExport();
  const list = id ? getList(id) : null;
  const [content] = useState(() => (id ? getHistory(id) : ''));

  if (!list || !id) {
    return (
      <div className="p-4 max-w-lg mx-auto space-y-4 text-center mt-12">
        <h1 className="text-2xl font-bold">List not found</h1>
        <Button onClick={() => navigate('/')}>Go home</Button>
      </div>
    );
  }

  const sections = parseHistorySections(content);
  const total = countDuels(content);

  return (
    <div className="p-4 max-w-lg mx-auto space-y-4">
      <div className="flex items-center gap-2">
        <Button asChild variant="ghost" size="icon" className="min-h-[44px] min-w-[44px]" aria-label="Back to list">
          <Link to={`/list/${id}`}>
            <ArrowLeft className="h-5 w-5" />
          </Link>
        </Button>
        <div className="min-w-0 flex-1">
          <h1 className="text-2xl font-bold truncate">{list.name}</h1>
          <p className="text-xs text-muted-foreground">Duel history</p>
        </div>
        {total > 0 && (
          <Button
            variant="outline"
            size="sm"
            onClick={() => exportHistory(list.id, list.name)}
            aria-label="Export history"
          >
            <Download className="h-4 w-4 mr-1" />
            Export
          </Button>
        )}
      </div>

      {sections.length === 0 ? (
        <div className="text-center py-12 space-y-2">
          <p className="text-muted-foreground">
            No duels yet. Play a session to start building history.
          </p>
          <Button onClick={() => navigate(`/list/${id}/duel`)}>
            Start a duel
          </Button>
        </div>
      ) : (
        <div className="space-y-4">
          <p className="text-xs text-muted-foreground">
            {total} {total === 1 ? 'duel' : 'duels'} recorded.
          </p>
          {sections.map((section) => (
            <section key={section.date} className="space-y-1">
              <h2 className="text-sm font-semibold sticky top-0 bg-background py-1">
                {section.date}
              </h2>
              <ul className="space-y-1 text-sm">
                {section.entries.map((entry, idx) => (
                  <li key={idx} className="border-l-2 pl-2">
                    {renderEntry(entry)}
                  </li>
                ))}
              </ul>
            </section>
          ))}
        </div>
      )}
    </div>
  );
}

function parseHistorySections(
  md: string,
): { date: string; entries: string[] }[] {
  if (!md.trim()) return [];
  const lines = md.split('\n');
  const sections: { date: string; entries: string[] }[] = [];
  let current: { date: string; entries: string[] } | null = null;
  for (const line of lines) {
    const m = /^##\s+(.+)$/.exec(line);
    if (m) {
      current = { date: m[1]!.trim(), entries: [] };
      sections.push(current);
      continue;
    }
    if (current && line.startsWith('- ')) {
      current.entries.push(line.slice(2));
    }
  }
  return sections.reverse();
}

function countDuels(md: string): number {
  const m = /^>\s*Auto-generated by DuelList\.\s*(\d+)\s*duels recorded\./m.exec(
    md,
  );
  return m ? parseInt(m[1]!, 10) : 0;
}

function renderEntry(raw: string): React.ReactNode {
  const stripped = raw.replace(/\s*\[[a-z0-9]{2,8}\]/gi, '');
  const win = /^(.+?)\s*>\s*(.+)$/.exec(stripped);
  if (win) {
    return (
      <>
        <strong>{win[1]}</strong>
        <span className="text-muted-foreground"> beat </span>
        <span>{win[2]}</span>
      </>
    );
  }
  const tie = /^(.+?)\s*=\s*(.+)$/.exec(stripped);
  if (tie) {
    return (
      <span className="text-muted-foreground">
        {tie[1]} = {tie[2]} (tied)
      </span>
    );
  }
  return stripped;
}
